-- MySQL Script generated by MySQL Workbench
-- Tue Jun 30 23:12:22 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema resurrex
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `resurrex` ;

-- -----------------------------------------------------
-- Schema resurrex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resurrex` DEFAULT CHARACTER SET utf8mb4 ;
USE `resurrex` ;

-- -----------------------------------------------------
-- Table `directory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `directory` ;

CREATE TABLE IF NOT EXISTS `directory` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `entry_offset` BIGINT(20) UNSIGNED NOT NULL,
  `parent_directory_offset` BIGINT(20) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_directory_1_idx` (`parent_directory_offset` ASC),
  INDEX `index3` (`entry_offset` ASC),
  CONSTRAINT `fk_directory_1`
    FOREIGN KEY (`parent_directory_offset`)
    REFERENCES `directory` (`entry_offset`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file` ;

CREATE TABLE IF NOT EXISTS `file` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `entry_offset` BIGINT(20) UNSIGNED NOT NULL,
  `parent_directory_offset` BIGINT(20) UNSIGNED NULL,
  `name` VARCHAR(255) NULL,
  `data_offset` BIGINT(20) UNSIGNED NULL,
  `data_len` BIGINT(20) UNSIGNED NULL,
  `is_contiguous` TINYINT(1) NULL,
  `is_copied_off` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_file_1_idx` (`parent_directory_offset` ASC),
  INDEX `index3` (`entry_offset` ASC),
  CONSTRAINT `fk_file_1`
    FOREIGN KEY (`parent_directory_offset`)
    REFERENCES `directory` (`entry_offset`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
